language: node_js
node_js:
  - 12

notifications:
    email: false

install:
  - cd backend && npm i
  - cd ../frontend && npm i

script:
  - cd ../backend && npm run lint
  - cd ../frontend && npm run lint
  - npm test
